I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 23, in script
    show kei default at images/kei/kei_default.png
  File "game/script.rpy", line 23, in <module>
    show kei default at images/kei/kei_default.png
NameError: name 'images' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 23, in script
    show kei default at images/kei/kei_default.png
  File "C:\Users\heave\OneDrive\renpy-8.3.7-sdk\renpy\ast.py", line 1124, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\heave\OneDrive\renpy-8.3.7-sdk\renpy\ast.py", line 1083, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\heave\OneDrive\renpy-8.3.7-sdk\renpy\ast.py", line 1083, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\heave\OneDrive\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\heave\OneDrive\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 23, in <module>
    show kei default at images/kei/kei_default.png
NameError: name 'images' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
VEIL_BNS 1.0
Mon May 26 11:42:29 2025
