I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 91, in script
    $ os.remove(file_path)
  File "game/script.rpy", line 91, in <module>
    $ os.remove(file_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\heave\\OneDrive\\2.8-Game-assessment\\VEIL_BNS\\game\\book.txt'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 91, in script
    $ os.remove(file_path)
  File "C:\Users\heave\OneDrive\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\heave\OneDrive\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 91, in <module>
    $ os.remove(file_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\heave\\OneDrive\\2.8-Game-assessment\\VEIL_BNS\\game\\book.txt'

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
VEIL_BNS 1.0
Sun Jun 15 10:02:12 2025
